"""
Django settings for booking_system_api project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oea8^9auwe2%za!%$z(nku#k6fy3zu&*meu=hc24195u=-&d=d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken', # Required by Djoser for token auth
    'corsheaders',
    'djoser',
    # Your apps
    'core',
]

REST_FRAMEWORK = {
           'DEFAULT_AUTHENTICATION_CLASSES': (
               'rest_framework.authentication.TokenAuthentication',
           ),
           'DEFAULT_PERMISSION_CLASSES': (
               'rest_framework.permissions.IsAuthenticated', # Default to authenticated access
           ),
       }

CORS_ALLOWED_ORIGINS = [
           "http://localhost:5173", # Your React frontend development server
           # Add your deployed frontend URL here later
       ]
       # Or for development, allow all (be careful in production!)
       # CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

DJOSER = {
           'PASSWORD_RESET_CONFIRM_URL': 'http://localhost:3000/password-reset/{uid}/{token}',
           'USERNAME_RESET_CONFIRM_URL': 'http://localhost:3000/username-reset/{uid}/{token}',
           'ACTIVATION_URL': 'http://localhost:3000/activate/{uid}/{token}',
           'SEND_ACTIVATION_EMAIL': False, # Set to True if you want email activation
           'SEND_CONFIRMATION_EMAIL': False, # Set to True if you want email confirmation
           'EMAIL': {
               'password_reset': 'djoser.email.PasswordResetEmail',
               # 'password_changed_confirmation': 'djoser.email.PasswordChangedConfirmationEmail',
           },
           'SERIALIZERS': {
               'user_create': 'djoser.serializers.UserCreateSerializer',
               'user': 'djoser.serializers.UserSerializer',
               'current_user': 'djoser.serializers.UserSerializer',
               'user_delete': 'djoser.serializers.UserDeleteSerializer',
           },
       }

ROOT_URLCONF = 'booking_system_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'booking_system_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
           'default': {
               'ENGINE': 'django.db.backends.postgresql',
               'NAME': 'booking_system_db',
               'USER': 'aleezaahmed',
               'PASSWORD': 'V9!tPz#4qR&nK8sL0w@eF3y',
               'HOST': 'localhost', # Or your DB host
               'PORT': '5432',
           }
       }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Email Configuration
# https://docs.djangoproject.com/en/6.0/topics/email/

EMAIL_USE = config('EMAIL_USE', default='console')  # 'console' or 'sendgrid'

if EMAIL_USE == 'sendgrid':
    # Production: SendGrid
    EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
    SENDGRID_API_KEY = config('SENDGRID_API_KEY', default='')
    DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@bookingsystem.com')
else:
    # Development: Console (prints to console)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@bookingsystem.local'
